version: '3.8'
services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: hyperfy_livekit_server
    hostname: livekit-server
    command: ["--dev", "--config", "/etc/livekit.yaml"]
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp" # For WebRTC/UDP
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
    restart: unless-stopped 