version: '3.8'

services:
  hyperfy-local:
    build:
      context: ../../
      dockerfile: docker/hyperfy/Dockerfile
      args:
        COMMIT_HASH: ${COMMIT_HASH:-local}
    container_name: hyperfy-local
    ports:
      - "3000:3000"  # Hyperfy server port
    environment:
      - NODE_ENV=production
      - COMMIT_HASH=${COMMIT_HASH:-local}
    volumes:
      # Mount .env file if it exists
      - ../../.env:/app/.env:ro
      # Optional: Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
    networks:
      - hyperfy-network

networks:
  hyperfy-network:
    driver: bridge

volumes:
  hyperfy-logs:
    driver: local 